
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 10 11:14:32 CST 2023
//----------------------------------------------------

package codigo;

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Nov 10 11:14:32 CST 2023
  */
public class Sintax extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\075\000\002\002\004\000\002\002\010\000\002\007" +
    "\003\000\002\007\003\000\002\007\003\000\002\007\003" +
    "\000\002\006\003\000\002\006\003\000\002\003\005\000" +
    "\002\003\002\000\002\004\010\000\002\004\002\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\010" +
    "\005\000\002\010\002\000\002\013\010\000\002\013\002" +
    "\000\002\015\005\000\002\015\003\000\002\014\003\000" +
    "\002\014\003\000\002\014\003\000\002\014\003\000\002" +
    "\014\003\000\002\014\003\000\002\014\003\000\002\017" +
    "\004\000\002\017\006\000\002\017\002\000\002\020\004" +
    "\000\002\020\006\000\002\020\002\000\002\011\020\000" +
    "\002\011\016\000\002\011\002\000\002\021\004\000\002" +
    "\021\004\000\002\021\004\000\002\021\004\000\002\021" +
    "\004\000\002\021\004\000\002\021\004\000\002\021\002" +
    "\000\002\023\007\000\002\022\010\000\002\024\007\000" +
    "\002\024\006\000\002\024\006\000\002\024\007\000\002" +
    "\024\007\000\002\025\005\000\002\026\007\000\002\027" +
    "\005\000\002\027\005\000\002\027\007\000\002\027\007" +
    "\000\002\030\005\000\002\030\003\000\002\030\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\220\000\004\037\005\001\002\000\004\002\222\001" +
    "\002\000\004\126\006\001\002\000\004\060\007\001\002" +
    "\000\014\002\ufff8\012\010\023\ufff8\036\ufff8\054\ufff8\001" +
    "\002\000\004\060\212\001\002\000\012\002\ufff1\023\ufff1" +
    "\036\ufff1\054\012\001\002\000\004\060\177\001\002\000" +
    "\010\002\uffdd\023\016\036\014\001\002\000\004\126\160" +
    "\001\002\000\004\002\000\001\002\000\004\126\017\001" +
    "\002\000\004\100\020\001\002\000\022\006\030\011\025" +
    "\030\031\032\026\041\022\045\024\046\023\101\uffe3\001" +
    "\002\000\004\126\155\001\002\000\010\060\uffe6\064\uffe6" +
    "\126\uffe6\001\002\000\010\060\uffe8\064\uffe8\126\uffe8\001" +
    "\002\000\010\060\uffea\064\uffea\126\uffea\001\002\000\010" +
    "\060\uffe9\064\uffe9\126\uffe9\001\002\000\010\060\uffeb\064" +
    "\uffeb\126\uffeb\001\002\000\004\101\032\001\002\000\010" +
    "\060\uffe7\064\uffe7\126\uffe7\001\002\000\010\060\uffec\064" +
    "\uffec\126\uffec\001\002\000\004\106\033\001\002\000\020" +
    "\006\030\011\025\030\031\032\026\041\022\045\024\046" +
    "\023\001\002\000\004\060\035\001\002\000\004\005\036" +
    "\001\002\000\004\060\037\001\002\000\016\016\uffd5\060" +
    "\042\100\054\126\052\127\050\130\053\001\002\000\016" +
    "\016\uffd5\060\042\100\054\126\052\127\050\130\053\001" +
    "\002\000\016\016\uffd5\060\042\100\054\126\052\127\050" +
    "\130\053\001\002\000\016\016\uffd5\060\042\100\054\126" +
    "\052\127\050\130\053\001\002\000\016\016\uffd5\060\042" +
    "\100\054\126\052\127\050\130\053\001\002\000\004\016" +
    "\146\001\002\000\014\064\143\074\060\075\062\076\064" +
    "\077\063\001\002\000\016\016\uffd5\060\042\100\054\126" +
    "\052\127\050\130\053\001\002\000\016\016\uffd5\060\042" +
    "\100\054\126\052\127\050\130\053\001\002\000\016\064" +
    "\ufffb\074\ufffb\075\ufffb\076\ufffb\077\ufffb\101\ufffb\001\002" +
    "\000\016\016\uffd5\060\042\100\054\126\052\127\050\130" +
    "\053\001\002\000\020\065\077\066\100\100\076\104\101" +
    "\106\075\111\102\112\103\001\002\000\016\064\ufffa\074" +
    "\ufffa\075\ufffa\076\ufffa\077\ufffa\101\ufffa\001\002\000\010" +
    "\100\056\127\050\130\053\001\002\000\004\101\070\001" +
    "\002\000\010\100\056\127\050\130\053\001\002\000\014" +
    "\074\060\075\062\076\064\077\063\101\uffc6\001\002\000" +
    "\010\100\uffff\127\uffff\130\uffff\001\002\000\010\100\056" +
    "\127\050\130\053\001\002\000\010\100\ufffe\127\ufffe\130" +
    "\ufffe\001\002\000\010\100\ufffc\127\ufffc\130\ufffc\001\002" +
    "\000\010\100\ufffd\127\ufffd\130\ufffd\001\002\000\004\101" +
    "\uffc7\001\002\000\004\101\067\001\002\000\004\101\uffc5" +
    "\001\002\000\014\064\072\074\060\075\062\076\064\077" +
    "\063\001\002\000\010\100\054\127\050\130\053\001\002" +
    "\000\004\060\073\001\002\000\016\016\uffc9\060\uffc9\100" +
    "\uffc9\126\uffc9\127\uffc9\130\uffc9\001\002\000\016\016\uffc8" +
    "\060\uffc8\100\uffc8\126\uffc8\127\uffc8\130\uffc8\001\002\000" +
    "\020\006\030\011\025\030\031\032\026\041\022\045\024" +
    "\046\023\001\002\000\012\101\125\127\116\130\112\131" +
    "\113\001\002\000\004\064\123\001\002\000\004\064\121" +
    "\001\002\000\012\127\116\130\112\131\113\134\114\001" +
    "\002\000\004\127\107\001\002\000\004\127\104\001\002" +
    "\000\004\064\105\001\002\000\004\060\106\001\002\000" +
    "\016\016\uffce\060\uffce\100\uffce\126\uffce\127\uffce\130\uffce" +
    "\001\002\000\004\064\110\001\002\000\004\060\111\001" +
    "\002\000\016\016\uffcf\060\uffcf\100\uffcf\126\uffcf\127\uffcf" +
    "\130\uffcf\001\002\000\006\064\ufff4\101\ufff4\001\002\000" +
    "\006\064\ufff3\101\ufff3\001\002\000\016\016\uffcd\060\uffcd" +
    "\100\uffcd\126\uffcd\127\uffcd\130\uffcd\001\002\000\004\064" +
    "\117\001\002\000\006\064\ufff5\101\ufff5\001\002\000\004" +
    "\060\120\001\002\000\016\016\uffd2\060\uffd2\100\uffd2\126" +
    "\uffd2\127\uffd2\130\uffd2\001\002\000\004\060\122\001\002" +
    "\000\016\016\uffd0\060\uffd0\100\uffd0\126\uffd0\127\uffd0\130" +
    "\uffd0\001\002\000\004\060\124\001\002\000\016\016\uffd1" +
    "\060\uffd1\100\uffd1\126\uffd1\127\uffd1\130\uffd1\001\002\000" +
    "\004\064\132\001\002\000\004\101\127\001\002\000\004" +
    "\064\130\001\002\000\004\060\131\001\002\000\016\016" +
    "\uffd3\060\uffd3\100\uffd3\126\uffd3\127\uffd3\130\uffd3\001\002" +
    "\000\004\060\133\001\002\000\016\016\uffd4\060\uffd4\100" +
    "\uffd4\126\uffd4\127\uffd4\130\uffd4\001\002\000\004\064\135" +
    "\001\002\000\004\060\136\001\002\000\016\016\uffcc\060" +
    "\uffcc\100\uffcc\126\uffcc\127\uffcc\130\uffcc\001\002\000\004" +
    "\016\uffdb\001\002\000\004\016\uffd7\001\002\000\004\016" +
    "\uffd8\001\002\000\010\100\054\127\050\130\053\001\002" +
    "\000\004\060\144\001\002\000\016\016\uffca\060\uffca\100" +
    "\uffca\126\uffca\127\uffca\130\uffca\001\002\000\016\016\uffcb" +
    "\060\uffcb\100\uffcb\126\uffcb\127\uffcb\130\uffcb\001\002\000" +
    "\004\060\147\001\002\000\010\002\uffdd\023\016\036\014" +
    "\001\002\000\004\002\uffdf\001\002\000\004\016\uffd9\001" +
    "\002\000\004\016\uffdc\001\002\000\004\016\uffda\001\002" +
    "\000\004\016\uffd6\001\002\000\006\063\156\101\uffe5\001" +
    "\002\000\022\006\030\011\025\030\031\032\026\041\022" +
    "\045\024\046\023\101\uffe3\001\002\000\004\101\uffe4\001" +
    "\002\000\004\100\161\001\002\000\022\006\030\011\025" +
    "\030\031\032\026\041\022\045\024\046\023\101\uffe0\001" +
    "\002\000\004\101\167\001\002\000\004\126\164\001\002" +
    "\000\006\063\165\101\uffe2\001\002\000\022\006\030\011" +
    "\025\030\031\032\026\041\022\045\024\046\023\101\uffe0" +
    "\001\002\000\004\101\uffe1\001\002\000\004\060\170\001" +
    "\002\000\004\005\171\001\002\000\004\060\172\001\002" +
    "\000\016\016\uffd5\060\042\100\054\126\052\127\050\130" +
    "\053\001\002\000\004\016\174\001\002\000\004\060\175" +
    "\001\002\000\010\002\uffdd\023\016\036\014\001\002\000" +
    "\004\002\uffde\001\002\000\012\002\uffef\023\uffef\036\uffef" +
    "\126\201\001\002\000\010\002\ufff2\023\ufff2\036\ufff2\001" +
    "\002\000\006\063\210\106\uffed\001\002\000\004\106\203" +
    "\001\002\000\020\006\030\011\025\030\031\032\026\041" +
    "\022\045\024\046\023\001\002\000\004\064\205\001\002" +
    "\000\004\060\206\001\002\000\012\002\uffef\023\uffef\036" +
    "\uffef\126\201\001\002\000\010\002\ufff0\023\ufff0\036\ufff0" +
    "\001\002\000\004\126\201\001\002\000\004\106\uffee\001" +
    "\002\000\014\002\ufff6\023\ufff6\036\ufff6\054\ufff6\126\214" +
    "\001\002\000\012\002\ufff9\023\ufff9\036\ufff9\054\ufff9\001" +
    "\002\000\004\062\215\001\002\000\010\127\116\130\112" +
    "\131\113\001\002\000\004\064\217\001\002\000\004\060" +
    "\220\001\002\000\014\002\ufff6\023\ufff6\036\ufff6\054\ufff6" +
    "\126\214\001\002\000\012\002\ufff7\023\ufff7\036\ufff7\054" +
    "\ufff7\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\220\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\010\001\001" +
    "\000\002\001\001\000\004\010\012\001\001\000\002\001" +
    "\001\000\004\011\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\014" +
    "\020\017\026\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\014\033\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\022" +
    "\006\044\021\043\022\050\023\040\024\042\025\037\026" +
    "\045\027\046\001\001\000\022\006\044\021\153\022\050" +
    "\023\040\024\042\025\037\026\045\027\046\001\001\000" +
    "\022\006\044\021\152\022\050\023\040\024\042\025\037" +
    "\026\045\027\046\001\001\000\022\006\044\021\151\022" +
    "\050\023\040\024\042\025\037\026\045\027\046\001\001" +
    "\000\022\006\044\021\150\022\050\023\040\024\042\025" +
    "\037\026\045\027\046\001\001\000\002\001\001\000\004" +
    "\007\141\001\001\000\022\006\044\021\140\022\050\023" +
    "\040\024\042\025\037\026\045\027\046\001\001\000\022" +
    "\006\044\021\137\022\050\023\040\024\042\025\037\026" +
    "\045\027\046\001\001\000\002\001\001\000\022\006\044" +
    "\021\136\022\050\023\040\024\042\025\037\026\045\027" +
    "\046\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\006\056\030\054\001\001\000\002\001\001\000\006\006" +
    "\056\030\065\001\001\000\004\007\060\001\001\000\002" +
    "\001\001\000\006\006\056\030\064\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\070\001" +
    "\001\000\006\006\044\027\073\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\014\133\001" +
    "\001\000\004\005\125\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\114\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\006\044\027\144\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\147\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\014\020\017" +
    "\156\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\014\162\020\161\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\014\162\020\165\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\006\044\021\172\022\050\023\040" +
    "\024\042\025\037\026\045\027\046\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\175\001\001\000\002" +
    "\001\001\000\006\013\177\015\201\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\203" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\013" +
    "\206\015\201\001\001\000\002\001\001\000\004\015\210" +
    "\001\001\000\002\001\001\000\004\004\212\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\215\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\004\220\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    
    public void syntax_error(Symbol s){
        this.s = s;
    }

    public Symbol getS(){
        return this.s;
}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintax$actions {
  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // AritmeticaAux ::= OperadorParentesisIzquierdo AritmeticaAux OperadorParentesisDerecho 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("AritmeticaAux",22, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // AritmeticaAux ::= ValorNum 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("AritmeticaAux",22, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // AritmeticaAux ::= ValorNum OperacionesAritmeticas AritmeticaAux 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("AritmeticaAux",22, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // Aritmetica ::= OperadorParentesisIzquierdo AritmeticaAux OperadorParentesisDerecho OperacionesAritmeticas Aritmetica 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Aritmetica",21, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // Aritmetica ::= OperadorParentesisIzquierdo AritmeticaAux OperadorParentesisDerecho OperadorPuntoYComa CambioLinea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Aritmetica",21, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // Aritmetica ::= ValorNum OperadorPuntoYComa CambioLinea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Aritmetica",21, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // Aritmetica ::= ValorNum OperacionesAritmeticas Aritmetica 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Aritmetica",21, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // Definicion ::= Identificador OperadorDosPuntos Tipo OperadorPuntoYComa CambioLinea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Definicion",20, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // AsignacionAritmetica ::= Identificador OperadorAsignacion AritmeticaTerminal 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("AsignacionAritmetica",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // Asignacion ::= Identificador OperadorDivisionAsignacion Entero OperadorPuntoYComa CambioLinea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Asignacion",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Asignacion ::= Identificador OperadorMultiplicacionAsignacion Entero OperadorPuntoYComa CambioLinea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Asignacion",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // Asignacion ::= Identificador OperadorDecremento OperadorPuntoYComa CambioLinea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Asignacion",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // Asignacion ::= Identificador OperadorIncremento OperadorPuntoYComa CambioLinea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Asignacion",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Asignacion ::= Identificador OperadorAsignacion ValorConst OperadorPuntoYComa CambioLinea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Asignacion",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // LlamadaFuncion ::= Identificador OperadorParentesisIzquierdo ValorConst OperadorParentesisDerecho OperadorPuntoYComa CambioLinea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LlamadaFuncion",16, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // LlamadaFuncionNoParam ::= Identificador OperadorParentesisIzquierdo OperadorParentesisDerecho OperadorPuntoYComa CambioLinea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LlamadaFuncionNoParam",17, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Sentencia ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Sentencia",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // Sentencia ::= AsignacionAritmetica Sentencia 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Sentencia",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Sentencia ::= Aritmetica Sentencia 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Sentencia",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Sentencia ::= Definicion Sentencia 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Sentencia",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Sentencia ::= Asignacion Sentencia 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Sentencia",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Sentencia ::= LlamadaFuncionNoParam Sentencia 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Sentencia",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Sentencia ::= LlamadaFuncion Sentencia 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Sentencia",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Sentencia ::= CambioLinea Sentencia 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Sentencia",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // SeccionFunciones ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SeccionFunciones",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // SeccionFunciones ::= ReservadaProcedure Identificador OperadorParentesisIzquierdo ParamsProcedures OperadorParentesisDerecho CambioLinea ReservadaBegin CambioLinea Sentencia ReservadaEnd CambioLinea SeccionFunciones 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SeccionFunciones",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-11)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // SeccionFunciones ::= ReservadaFunction Identificador OperadorParentesisIzquierdo ParamsFunciones OperadorParentesisDerecho OperadorDosPuntos Tipo CambioLinea ReservadaBegin CambioLinea Sentencia ReservadaEnd CambioLinea SeccionFunciones 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SeccionFunciones",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-13)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // ParamsProcedures ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ParamsProcedures",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // ParamsProcedures ::= Tipo Identificador OperadorComa ParamsProcedures 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ParamsProcedures",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ParamsProcedures ::= Tipo Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ParamsProcedures",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ParamsFunciones ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ParamsFunciones",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ParamsFunciones ::= Tipo Identificador OperadorComa ParamsFunciones 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ParamsFunciones",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ParamsFunciones ::= Tipo Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ParamsFunciones",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Tipo ::= ReservadaReal 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Tipo",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Tipo ::= ReservadaBoolean 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Tipo",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Tipo ::= ReservadaString 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Tipo",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Tipo ::= ReservadaChar 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Tipo",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Tipo ::= ReservadaShortInt 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Tipo",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Tipo ::= ReservadaLongInt 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Tipo",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Tipo ::= ReservadaInt 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Tipo",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // LoopIdentificadores ::= Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LoopIdentificadores",11, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // LoopIdentificadores ::= Identificador OperadorComa LoopIdentificadores 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LoopIdentificadores",11, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // LoopVar ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LoopVar",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // LoopVar ::= LoopIdentificadores OperadorDosPuntos Tipo OperadorPuntoYComa CambioLinea LoopVar 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LoopVar",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // SeccionGlobales ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SeccionGlobales",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SeccionGlobales ::= ReservadaVar CambioLinea LoopVar 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SeccionGlobales",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ValorConst ::= String 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ValorConst",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // ValorConst ::= Flotante 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ValorConst",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // ValorConst ::= Entero 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ValorConst",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // LoopConst ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LoopConst",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // LoopConst ::= Identificador OperadorIgual ValorConst OperadorPuntoYComa CambioLinea LoopConst 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LoopConst",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SeccionConst ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SeccionConst",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SeccionConst ::= ReservadaConst CambioLinea LoopConst 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SeccionConst",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ValorNum ::= Flotante 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ValorNum",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // ValorNum ::= Entero 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ValorNum",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // OperacionesAritmeticas ::= OperadorDivision 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OperacionesAritmeticas",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // OperacionesAritmeticas ::= OperadorMultiplicacion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OperacionesAritmeticas",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // OperacionesAritmeticas ::= OperadorResta 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OperacionesAritmeticas",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // OperacionesAritmeticas ::= OperadorSuma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OperacionesAritmeticas",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Inicio ::= ReservadaProgram Identificador CambioLinea SeccionConst SeccionGlobales SeccionFunciones 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Inicio",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

