
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 07 19:03:12 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ReservadaSet = 34;
  public static final int ReservadaLabel = 23;
  public static final int OperadorResta = 59;
  public static final int ε = 88;
  public static final int ReservadaWith = 44;
  public static final int ReservadaForward = 16;
  public static final int ReservadaProcedure = 28;
  public static final int ReservadaEnd = 12;
  public static final int ReservadaProgram = 29;
  public static final int ReservadaReal = 31;
  public static final int ReservadaType = 40;
  public static final int OperadorDesplazamientoIzquierdaAsignacion = 75;
  public static final int OperadorDesplazamientoDerechaAsignacion = 76;
  public static final int ReservadaRead = 30;
  public static final int OperadorPuntoYComa = 50;
  public static final int ReservadaRepeat = 33;
  public static final int OperadorCorcheteDerecho = 65;
  public static final int OperadorAsignacion = 66;
  public static final int ReservadaBegin = 3;
  public static final int OperadorMenorQue = 56;
  public static final int OperadorDesplazamientoDerecha = 73;
  public static final int CambioLinea = 46;
  public static final int OperadorParentesisIzquierdo = 62;
  public static final int OperadorNot = 77;
  public static final int OperadorComa = 49;
  public static final int OperadorOr = 78;
  public static final int OperadorDiferente = 57;
  public static final int String = 87;
  public static final int Caracter = 47;
  public static final int ReservadaString = 36;
  public static final int OperadorMod = 82;
  public static final int ReservadaThen = 37;
  public static final int ReservadaGoto = 18;
  public static final int OperadorMultiplicacionAsignacion = 71;
  public static final int ReservadaConst = 8;
  public static final int OperadorMultiplicacion = 60;
  public static final int OperadorMayorOIgualQue = 53;
  public static final int ReservadaUntil = 41;
  public static final int ReservadaShortInt = 35;
  public static final int OperadorSuma = 58;
  public static final int ReservadaDo = 9;
  public static final int ReservadaPacked = 27;
  public static final int OperadorMenorOIgualQue = 55;
  public static final int ReservadaTrue = 39;
  public static final int OperadorDiv = 81;
  public static final int ReservadaNil = 25;
  public static final int ReservadaBoolean = 4;
  public static final int ReservadaChar = 7;
  public static final int ReservadaVar = 42;
  public static final int ReservadaLongInt = 24;
  public static final int OperadorRestaAsignacion = 70;
  public static final int ReservadaFalse = 13;
  public static final int ReservadaArray = 2;
  public static final int Flotante = 86;
  public static final int EOF = 0;
  public static final int ReservadaElse = 11;
  public static final int OperadorDesplazamientoIzquierda = 74;
  public static final int OperadorMayorQue = 54;
  public static final int OperadorParentesisDerecho = 63;
  public static final int ReservadaIn = 20;
  public static final int ReservadaFunction = 17;
  public static final int OperadorIncremento = 51;
  public static final int OperadorIgual = 48;
  public static final int ReservadaIf = 19;
  public static final int OperadorDosPuntos = 68;
  public static final int error = 1;
  public static final int ReservadaOf = 26;
  public static final int ReservadaWrite = 45;
  public static final int Error = 83;
  public static final int ReservadaInline = 21;
  public static final int OperadorCorcheteIzquierdo = 64;
  public static final int ReservadaFor = 15;
  public static final int ReservadaWhile = 43;
  public static final int ReservadaRecord = 32;
  public static final int OperadorDivisionAsignacion = 72;
  public static final int Identificador = 84;
  public static final int ReservadaInt = 22;
  public static final int OperadorDecremento = 52;
  public static final int Entero = 85;
  public static final int ReservadaFile = 14;
  public static final int OperadorDivision = 61;
  public static final int ReservadaTo = 38;
  public static final int OperadorPunto = 67;
  public static final int OperadorAnd = 79;
  public static final int ReservadaDownto = 10;
  public static final int ReservadaCase = 6;
  public static final int OperadorSumaAsignacion = 69;
  public static final int OperadorXor = 80;
  public static final int ReservadaByte = 5;
}

